name: Deploy Next.js App to S3

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static site
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: eu-west-1

      - name: Install s5cmd
        run: |
          curl -L -o s5cmd.tar.gz https://github.com/peak/s5cmd/releases/download/v2.2.2/s5cmd_2.2.2_Linux-64bit.tar.gz
          tar -xzf s5cmd.tar.gz
          sudo mv s5cmd /usr/local/bin/
          s5cmd version

      - name: Upload site (no-cache) - fast
        run: |
          s5cmd sync \
            --delete \
            --exclude "_next/*" \
            --cache-control "public,max-age=0,must-revalidate" \
            out/ s3://anirank.ie/

      - name: Upload _next (long cache) - fast
        run: |
          s5cmd sync \
            --delete \
            --cache-control "public,max-age=31536000,immutable" \
            out/_next/ s3://anirank.ie/_next/

      - name: Invalidate CloudFront (small)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/" "/index.html"
